# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1227731381dfdd27fc58f10cc3a24ec3d907b98a89ec959866486ba6369ca2c9fb6b6ad5253e68bd68f1786e8a5ec7bc3470264f971a9efec18823d307fbb62

test:
  secret_key_base: 028cfa110efabbe50b1be8e0cb932f9e9bf0332566981974341ad981b5c43bed080b68d28bd4e300dad18c650fb6e7c0e0ff902b4d0d5d84e51476a6598b21b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
